### ISSUE TITLE
Data to Server communication

### ISSUE THREAD

**Issue by Sidewayswalker** [PrimeAcademy/biscayne-syllabus#13]
## Description

STEVEN KARL

**What do you want to happen?**
I want the expansive data (Guests, phoneNumbers) to be sent over to the server

**What is actually happening?**
I had the data working for 1 person then I got the expansion inputs working and the data failed. 

I'm following a bunch of console.logs to insure that I'm following the data. but I'm not getting a resolution.

I asked Suz. 

console log for the win. every step in the process. 

Main Branch

Breaks are good.

I was hoping I could remote call you and screen share.

**Comment by matthew-black** [comment]
Just had to modify the Saga function to no longer be hardcoded to expect just one guest, then update the POST route code to match the naming conventions of your guest objects. :)
