### ISSUE TITLE
My Update Route is not working as i expected

### ISSUE THREAD

**Issue by AsiaOsman06** [PrimeAcademy/biscayne-syllabus#15]
## Description

**Your Real Name**

Asia Osman

**What do you want to happen?**
my update  button is working when i click on it but my conditional statement is not working
**What is actually happening?**

it doesn't show any error that i can check

## Screenshots / Code Snippets

just the button is still showing complete beside to be not complete but the boolean is working as needed
## What did you try? Who did you ask?
jason

## What branch is your code on? Did you git push?

https://github.com/AsiaOsman06/FitnessFollower_App
## When was the last time you took a break?
10 min ago

**Comment by matthew-black** [comment]
Need more info.

* Which button? In which component file?
* Which Saga function is the button meant to call?
* Which route does the Saga function interact with?
