### ISSUE TITLE
My Exercise.jsx file was giving me an infinite loop Delete 

### ISSUE THREAD

**Issue by AsiaOsman06** [PrimeAcademy/biscayne-syllabus#18]
## Description

**Your Real Name**

Asia Osman

**What do you want to happen?**
when i tried to add new exercise it does add but with different infinity empty delete button
**What is actually happening?**

## Screenshots / Code Snippets
<img width="1680" alt="Screenshot 2024-05-31 at 1 44 16 PM" src="https://github.com/PrimeAcademy/biscayne-syllabus/assets/115678840/17170d54-58a4-401a-b247-6ea15be460dd">

## What branch is your code on? Did you git push?
https://github.com/AsiaOsman06/FitnessFollower_App

**Comment by matthew-black** [comment]
It was an infinite loop because your `addExercise` Saga function was calling itself over and over again. We needed to modify it to call the `fetchExercises` function after a successful `POST` request.
