### ISSUE TITLE
halp! Not sure why my API Key is undefined / 'process undefined'

### ISSUE THREAD

**Issue by janetscanlon** [PrimeAcademy/biscayne-syllabus#19]
## Description

**Your Real Name**

janet

**What do you want to happen?**
I want my CareTeamRegistration file to successfully be passed the API key in my .env file ! 
**What is actually happening?**

booooo it's being read as undefined. Either I get a Process is undefined or reading '.setAPIKey' is undefined! 
![Screenshot 2024-06-17 at 10 04 01 AM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/90e6866e-bd16-41c4-bfed-b5682af2c13b)

## Screenshots / Code
![Screenshot 2024-06-17 at 10 02 51 AM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/36538f17-9451-43b4-93fd-2a6601d42479)
![Screenshot 2024-06-17 at 10 03 03 AM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/55892e25-a4b3-4a32-bf7c-429904709640)
![Screenshot 2024-06-17 at 10 03 22 AM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/f6674e9d-a88f-46b9-8af8-d55a8352c46a)
![Screenshot 2024-06-17 at 10 03 34 AM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/e1866a93-b7fd-4c2e-b757-f1b7a640db43)
 Snippets

## What did you try? Who did you ask?
tried/asked teammates! Also solo debugging last night for a few hours. Stackoverflow etc 

I've changing syntax but it seems that my apiKey is being read as undefined and I'm not sure why :D 

Google recommended that I import dotenv directly into the file where I want to use process.env.myapikey but I am getting a strange error that 'process' is undefined
## What branch is your code on? Did you git push?
my branch is pushed up to github: 
feature/CareTeamRegistration

**Comment by matthew-black** [comment]
Talked through the need to do the `sgMail` stuff server-side. :)
