### ISSUE TITLE
Needing Conceptual Assistance - Month/Year checking and providing Alerts  

### ISSUE THREAD

**Issue by kristinhuot** [PrimeAcademy/biscayne-syllabus#23]
## Description

**Your Real Name**
Kristin

**What do you want to happen?**
I am working on the MyData page. I am needing to render alerts, only if a user is missing inputs and only from since the user signed up. 

<img width="852" alt="image" src="https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/f3f80f2a-ae9c-411f-969a-78be1dffe3aa">

**What is actually happening?**

I am struggling with the conceptual breakdown and getting confused as I break it down. So far, I've been able to add a field to the database that logs the date when a user creates an account. We have a GET route that should show all of a user's input entries (not currently working correctly, bug 1). From there, my thought was to use a date library (date-fns) to help with some of the complexity around calculating the date range. 

In essence, my thought is to calculate the dates between when a user signs up and today's date. Then compare that to the data we have in the database and show an alert only if the data is missing. However, this is proven to be super complicated. 

We'd also like to add a second alert that verifies if a user has completed a recommendation or not but I haven't been able to even get to that. I'm on day 2 of working on this so needing to unblock once and for all!

## Screenshots / Code Snippets

![image](https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/3d71b906-ab69-40a8-8335-65f92e985f32)

![image](https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/462d33bb-c37b-4c6c-b0a1-ac12597336d4)

## What did you try? Who did you ask?
I've tried working this out with Lisa, Tristan, and Marcos. I've tried referencing guide documents, google, AI. 

## What branch is your code on? Did you git push?
Yes and it is on feature-my_data_page

**Comment by matthew-black** [comment]
* https://stackoverflow.com/questions/9134497/mysql-datatype-to-store-month-and-year-only#:~:text=Just%20store%20it%20as%20a%20complete%20date

I reckon this 👆 idea will make it a bit more straightforward.

What we'll need to be able to do:

* For a given user:
  * Figure out what MM/YYYY they registered.
  * Figure out which MM/YYYY they have *not* submitted data for, since (and including) the registration month.

**Comment by matthew-black** [comment]
Pew pew!
* https://github.com/matthew-black/wacky_year_month_fun
