### ISSUE TITLE
Socket.io Guidence 

### ISSUE THREAD

**Issue by janetscanlon** [PrimeAcademy/biscayne-syllabus#24]
## Description

**Your Real Name**
Janet (and Mustafe)

**What do you want to happen?**
I want to be able to access user context from passport/session while using socket.io and the socket.io pg adapter. 

**What is actually happening?**
I am able to successfully create a table row with socket.io and socket.io pg adapter. However, now I'd like to have access to req.user.id and other properties. And perhaps the answer is I just have to send that user from the client side instead of having the convenience of retrieving it from passport... Since passport is not directly compatible with socket.io 

## Screenshots / Code Snippets

![Screenshot 2024-06-20 at 11 02 22 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/7d4fadfb-9b97-47dd-a8f4-98c387b11231)
![Screenshot 2024-06-20 at 11 02 33 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/4a15db27-bd17-4dd2-8b86-e56010ce72ae)
![Screenshot 2024-06-20 at 11 02 47 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/b3589147-43d1-41f6-8267-a6c01e44a8b3)

## What did you try? Who did you ask?
googling, spiking with Mustafe. 

https://github.com/socketio/socket.io/tree/main/examples/passport-example
https://socket.io/how-to/use-with-passport

it looks like there should be a way to integrate passport with socket.io but I don't know enough about the staring repo infrastructure to apply what they're trying to tell me in the documentation (it's not great documentation). I don't know enough about middleware, passport etc to apply. 

 

## What branch is your code on? Did you git push?
feature/messagestutorial 

## When was the last time you took a break?
just came back from a dinner with some girlies!

**Comment by DoctorHowser** [comment]
https://socket.io/how-to/use-with-passport Take a look at this

**Comment by janetscanlon** [comment]
Hi Dane, I cited this in the issue. I've looked over this resource. Looking for guidance on how to parse through it and what I need to apply with our repo infrastructure

**Comment by matthew-black** [comment]
@janetscanlon If you get blocked on this, please reopen the issue!
