### ISSUE TITLE
Home Page/ MUI/ SX

### ISSUE THREAD

**Issue by Heather-Haymond** [PrimeAcademy/biscayne-syllabus#26]
## Description

Heather Haymond

**What do you want to happen?**
I want to style the home page with MUI so that each section will fill the whole screen and implement snap scroll to navigate each section.

**What is actually happening?**
each section is small/not taking up a full screen space. I'm using SX which is ok, but less than ideal. 
snap scroll is working fine. 

## Screenshots / Code Snippets

<img width="1096" alt="Screenshot 2024-06-25 at 2 05 20 PM" src="https://github.com/PrimeAcademy/biscayne-syllabus/assets/119762619/c286eb10-1149-4e36-814f-6b6c5deed195">
<img width="966" alt="Screenshot 2024-06-25 at 2 04 32 PM" src="https://github.com/PrimeAcademy/biscayne-syllabus/assets/119762619/a7a19c9e-ad24-420c-b892-1c42f2773b3d">

## What did you try? Who did you ask?
Team members, google, chatGPT... I tried to adjust the height of the container, 100% 100hv and am tempted to adjust margin and padding in reference to css, but trying to be mindful of time and collaboration 

 researching, googling, trying various solutions. 
 It seems that adjusting the height of the container to 100vh with flex to make it dynamic should work

## What branch is your code on? Did you git push?
feature/new_home_page

## When was the last time you took a break? 
lunch... but I've been looking at this for days and took real breaks

Thaaaaank you!!

**Comment by matthew-black** [comment]
Fill it up with content! Then, once you're to that point, take a look at it and think how it should be styled.
