### ISSUE TITLE
Cannot Get MUI dayjs function to work to insert a DayPicker 

### ISSUE THREAD

**Issue by kristinhuot** [PrimeAcademy/biscayne-syllabus#3]
I'm trying to use MUI's DayPicker component to insert a calendar for users to pick their birthday.

**Your Real Name**
Kristin 

**What do you want to happen?**
I want the datepicker to render on the DOM 

**What is actually happening?**
![image](https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/8d2c361e-0bfe-45bd-8794-95cac5763344)

## Screenshots / Code Snippets
![image](https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/e231d6e3-3c0c-4fb6-ab86-bc4032b477ce)

## What did you try? Who did you ask?
I've tried installing all the required dependencies (DayJS, MUIDatePickers, etc). Tried googling, using stackoverflow, and Claude. 
I tried asking Jason and he couldn't figure it out either. 

## What branch is your code on? Did you git push?

Oops, it's on main right now. 

## When was the last time you took a break?
52 minutes ago

**Comment by matthew-black** [comment]
Just had to restart server/client. 🪄
