### ISSUE TITLE
Typing NPM Run Client is trying to start the server 

### ISSUE THREAD

**Issue by kristinhuot** [PrimeAcademy/biscayne-syllabus#4]
## Description
![image](https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/15df87df-c8f7-414d-b26b-d869333340e7)

**Your Real Name**
Kristin

**What do you want to happen?**
I want to have vite to run :(

**What is actually happening?**
Error above 

## Screenshots / Code Snippets

Above

## What did you try? Who did you ask?
Lisa

## What branch is your code on? Did you git push?
It was on a feature branch but I pushed it to main before I tested it. Ugh. 
.

**Comment by matthew-black** [comment]
```
npm run client
npm run server
```

🙂

**Comment by kristinhuot** [comment]
Can I edit this ticket to be the actual PUT route issue I'm having?

**Comment by matthew-black** [comment]
@kristinhuot I'd close this and document that issue separately.
