### ISSUE TITLE
Help with conceptual data structures for rendering my like count on a book review

### ISSUE THREAD

**Issue by janetscanlon** [PrimeAcademy/biscayne-syllabus#6]
## Description

**Your Real Name**

Janet Scanlon

**What do you want to happen?**
I want to be able to render the like count for each review post 
**What is actually happening?**
My likeReducer is being updated for each post (which is what I want) but it's only rendering the data stored in the latest update. I'd ideally like to be able to render the reducer data for each iteration of posts -- Currently I believe I have my code set up so that it runs my "FETCH_REVIEW_LIKES" every time a post is rendered. UseEffect (Line 22 in the ReviewPost.jsx component.) 

I've included pictures of my sql query: 
SELECT * FROM "review_likes"
WHERE "review_id" = $1; 

using req.params to send over the review id.

Saving the response.data in an array in the reducer. 

no errors 

## Screenshots / Code Snippets

![Screenshot 2024-05-26 at 4 04 43 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/69e2b9cb-843a-4eeb-bb44-f5f8b373ad5f)
![Screenshot 2024-05-26 at 4 05 31 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/99ca6ffd-7e33-413a-bc35-bf455e683968)
![Screenshot 2024-05-26 at 4 12 22 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/4b4a2750-a200-40eb-a82e-14389e334d2b)
![Screenshot 2024-05-26 at 4 12 40 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/69414b1f-adf4-45cc-af4c-ecc83c17d8d2)
![Screenshot 2024-05-26 at 4 12 54 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/7a4f28a2-a020-4802-bdef-ee8820f2db3a)
![Screenshot 2024-05-26 at 4 13 05 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/f92d267b-2ff3-4896-9c37-c3a54899db4c)
![Screenshot 2024-05-26 at 4 13 48 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/9a8ec9a3-78e7-442f-8085-ca138e0d1639)
![Screenshot 2024-05-26 at 4 14 18 PM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/156254619/d828247d-0f36-42a0-ba83-7186e090f5b9)

## What did you try? Who did you ask?
Talked over conceptual concepts with kristin and alex -- Thought about restructuring my db Table but I feel like I should be able to make this work?? I'm just missing some pieces. 

no debugging ... just help with concepts on how to execute 

## What branch is your code on? Did you git push?
feature/likes

## When was the last time you took a break?
20 minutes ago

**Comment by janetscanlon** [comment]
branch is pushed up to github!

**Comment by matthew-black** [comment]
We're going to modify the GET /reviews route to include a `like_count` property on each review object.
