### ISSUE TITLE
Issue in Fetch in Form Edit - rendering HTML 

### ISSUE THREAD

**Issue by kristinhuot** [PrimeAcademy/biscayne-syllabus#7]
## Description

I am working on the edit flight function within the my flights component. The input fields with prepopulated flight data is not appearing. Instead, HTML is showing as the response.data and the store value. The console log in my SQL query is not showing on the server. I was able to manually get the route to show by putting it into the browser, but the data is not correctly going from the Saga --> SQL --> Store. 

**Your Real Name**
Kristin

**What do you want to happen?**

I would like the function to correctly render the pre-populated data and input from the specific flight id that I am providing. 

**What is actually happening?**

![image](https://github.com/PrimeAcademy/biscayne-syllabus/assets/151860024/e75d14c5-fc71-42f9-9078-f3e823b9ceb1)

## What did you try? Who did you ask?
Googling, troubleshooting with AI, Janet, Lisa. 

I was able to determine the general area of my issue through console logs. I am also wondering if not having the following in my routes is causing the problem? I was recently made aware we might need this?

const config = {
      headers: { 'Content-Type': 'application/json' },
      withCredentials: true,
    }

## What branch is your code on? Did you git push?

feature-edit-button

## When was the last time you took a break?

20 mins ago

**Comment by matthew-black** [comment]
Just an annoying `axios({})` vs `axios.get()` mistake. All good now!
