### ISSUE TITLE
Assistance Passing the Correct Data for the Updating my Medications

### ISSUE THREAD

**Issue by mustafehassan00** [PrimeAcademy/biscayne-syllabus#9]
## Description

**Your Real Name**

Mustafe Hassan 

**What do you want to happen?**
Whenever I click Edit I want to grab that data from whatever  User medication I want to Update/Edit

**What is actually happening?**

Once I click the edit button I am receiving a (Payload Too Large) error inside the terminal and console

## Screenshots / Code Snippets

![Screenshot 2024-05-28 at 11 56 53 AM](https://github.com/PrimeAcademy/biscayne-syllabus/assets/155122726/7803c7a9-5256-47e8-82ea-b5c88c7bc3bf)
<img width="1440" alt="Screenshot 2024-05-28 at 11 58 04 AM" src="https://github.com/PrimeAcademy/biscayne-syllabus/assets/155122726/e854dfdc-19a2-46e0-93d8-e4b88d013ce0">
![Screenshot 2024-05-28 at 11 58 04 AM 2](https://github.com/PrimeAcademy/biscayne-syllabus/assets/155122726/6e5e12e8-b852-458f-926a-8bbb08ac96f9)

## What did you try? Who did you ask?

I googled the error and the only solution is to increase the payload limit which I don't think I am qualified to do yet

it Is telling me to increase my payload limit

## What branch is your code on? Did you git push?

main branch , & yes 

## When was the last time you took a break?
5 Minutes ago

**Comment by mustafehassan00** [comment]
never mind I fixed it.
I have a new Issue now where The edit button is now clearing out the data from the database

**Comment by matthew-black** [comment]
Delete button is working! Now you just need to follow this whole song and dance to get your edit form working for a medication:
* https://zoom.us/rec/share/RqVHL4li12Q7-JYVT7M8UiQWnX3iSqYM3U3asu0Wb5Ejz04-q068i0KAewo0g8mS.I7_vMgWI1ao4WlRE?startTime=1716561250000
